{
 "title": "OpenVPN Server",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Top Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(count_values(\"connection_time\", count_over_time(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))by(common_name)>1)",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openvpn_up{job=\"qxy-openvpn\"}"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table-old",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(label_replace(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address))"
    },
    {
     "expr": "sum(label_replace(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openvpn_server_connected_clients"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds{job=\"qxy-openvpn\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{common_name=~\"[a-zA-Z]+\"}) or absent(count(openvpn_server_client_received_bytes_total{common_name=~\"[a-zA-Z]+\"}))-1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{common_name=~\"[a-z]+\"}) or absent(count(openvpn_server_client_received_bytes_total{common_name=~\"[a-z]+\"}))-1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Top 6 Client Network Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Rx"
    },
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Tx"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name)))",
     "legendFormat": "Rx - Others"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1m]))by(common_name)))",
     "legendFormat": "Tx - Others"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort(sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Clients" }
   ],
   "targets": [
    {
     "expr": "sum(openvpn_server_connected_clients)",
     "legendFormat": "Connected OpenVPN Clients"
    }
   ]
  }
 ]
}